### ISSUE TITLE
Review infra PRs for modifications

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/prod-playbooks#16]
@manics pointed out that a number of discussions had been had regarding the prod playbooks. The ones I've found are:

 * [ ] https://github.com/openmicroscopy/infrastructure/pull/255
 * [ ] https://github.com/openmicroscopy/infrastructure/pull/268#issuecomment-301858051
 * [ ] https://github.com/openmicroscopy/infrastructure/pull/271
 * [ ] https://github.com/openmicroscopy/infrastructure/pull/273
 * [ ] https://github.com/openmicroscopy/infrastructure/pull/276

These should be reviewed for modifications. Positive outcomes would include:

 * trusting `-C --diff` on production hosts
 * trusting `site.yml` to run periodically
 * refactoring into idempotent tasks
 * reducing duplication between the playbooks here

**Comment by manics** [comment]
Shall we close this since everything is in https://github.com/openmicroscopy/prod-playbooks/ ?

**Comment by joshmoore** [comment]
Did you look at those issues? Did a PR get opened for the various issues?

**Comment by joshmoore** [comment]
K, thanks.
